title: Anne Morgan
description: >
  <b>Librarian</b>
  <br>
  <p>MSIS</p>
  <a href="/pdf/20241007CV.pdf" target="_blank">CV</a> |
  <a href="https://github.com/anneemorgan/" target="_blank">GitHub</a> |
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/" target="_blank">LinkedIn</a>
  <br>
  <br>
      <a
    id="cy-effective-orcid-url"
    class="underline"
     href="https://orcid.org/0000-0003-2468-493X"
     target="orcid.widget"
     rel="me noopener noreferrer"
     style="vertical-align: top">
     <img
        src="https://orcid.org/sites/default/files/images/orcid_16x16.png"
        style="width: 1em; margin-inline-start: 0.5em"
        alt="ORCID iD icon"/>
      https://orcid.org/0000-0003-2468-493X
    </a>
  
  
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
google_analytics: G-5RZDWDG0X7
