title: Anne Morgan # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="/pdf/UpdatedResumeAEM.pdf">Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/">LinkedIn</a>
  <br><br>
  <b>Contact me</b>
  <p>anneemorgan20@gmail.com</p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
