title: Anne Morgan # your name (or website title) here
logo: "/images/20210402_cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me 
  <br><br>
  I support research and access to knowledge. 
  <br><br>
  My undergraduate education, at Truman State University, immersed me in historical research. 
  I realized that research is like detective work. Each new lead builds on the accumulated knowledge that came before it.
  My graduate education in the Information Studies program at the University of Texas at Austin, in addition to various positions in libraries and archives, 
  pulled me even more strongly towards this way of working. Professionally, I aim to facilitate knowledge diffusion and to contribute to the collaborative efforts 
  needed to make this diffusion happen, including: digitization, cataloging, metadata management, and archiving. 
  I also edit Wikipedia articles.
  <br><br>
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
