title: Anne Morgan # your name (or website title) here
logo: "/images/20210402_cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I support research and access to knowledge.
  <br><br>
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
