title: Anne Morgan # your name (or website title) here
logo: "/images/20210402_134745111.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me 
  <br><br>
  I am a graduate student at the University of Texas at Austin, pursuing a Master of Science in Information Studies.
  <br><br>
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
