title: Anne Morgan # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Medical librarian</b>
  <p>Contact me: anneemorgan20@gmail.com</p>
  <a href="https://orcid.org/0000-0003-2468-493X">
<img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" />
https://orcid.org/0000-0003-2468-493X
</a>
  <a href="/pdf/UpdatedCVAEM.pdf" target="_blank">CV</a> |
  <a href="https://github.com/anneemorgan/" target="_blank">GitHub</a> |
  <a href="https://www.linkedin.com/in/anne-elizabeth-morgan/" target="_blank">LinkedIn</a>


permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
